# Generated by Django 3.2.9 on 2021-11-22 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='title')),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'unique_together': {('category_name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
                ('unit_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(default=None, upload_to='images', verbose_name='Thumbnail')),
                ('other_image1', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('other_image2', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('unit_price', models.FloatField()),
                ('availability_wef_date', models.DateField(default=datetime.date)),
                ('availability_wet_date', models.DateField(default=datetime.date)),
                ('location', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.category', verbose_name='Category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.units', verbose_name='Unit')),
            ],
        ),
    ]
