# Generated by Django 3.2.9 on 2021-11-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability_wef_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability_wet_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
    ]
