# Generated by Django 3.2.9 on 2021-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_farmer_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
