# Generated by Django 3.2.9 on 2021-11-25 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
