# Generated by Django 3.2.9 on 2021-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_product_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
