# Generated by Django 3.2.9 on 2021-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_order_other_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
