# Generated by Django 3.2.9 on 2021-12-10 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0010_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='total_cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_wef_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Available from'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_wet_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Available until'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default=None, upload_to='images/%Y/%m/%d', verbose_name='Thumbnail'),
        ),
    ]
