# Generated by Django 3.2.9 on 2021-12-10 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0011_auto_20211210_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_value', models.FloatField()),
                ('status', models.CharField(choices=[('Shipped', 'Shipped'), ('Canceled', 'Canceled'), ('On-route', 'On-route'), ('Delivered', 'Delivered')], max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.order')),
                ('other_Charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.other_charges')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('M-pesa', 'M-pesa'), ('Cash', 'Cash')], max_length=10)),
                ('total_amount', models.FloatField()),
                ('ref', models.CharField(max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Other_Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_charges_total_price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.order')),
                ('other_Charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.other_charges')),
            ],
        ),
    ]
