# Generated by Django 3.2.9 on 2021-12-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0012_order_other_charges_payment_purchaseorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Other_Charges',
            new_name='OrderOtherCharges',
        ),
    ]
