# Generated by Django 3.2.9 on 2021-12-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInformation', '0001_initial'),
        ('supply', '0014_rename_other_charges_othercharges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInformation.customer'),
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
