# Generated by Django 3.2.9 on 2021-12-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('supply', '0016_auto_20211214_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderothercharges',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderothercharges',
            name='other_Charges',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='other_Charges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.othercharge'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
        migrations.DeleteModel(
            name='OrderOtherCharges',
        ),
        migrations.DeleteModel(
            name='OtherCharges',
        ),
    ]
