# Generated by Django 3.2.9 on 2021-12-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0018_auto_20211218_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mode',
            new_name='payment_mode',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='payment_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='ref',
            new_name='payment_ref',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total_amount',
            new_name='payment_total_price',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='date',
            new_name='purchase_order_date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_id',
            new_name='purchase_order_order_id',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='other_Charges',
            new_name='purchase_order_other_Charges',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_value',
            new_name='purchase_order_total_value',
        ),
    ]
