# Generated by Django 3.2.9 on 2021-12-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0019_auto_20211220_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order_other_Charges',
            new_name='purchase_order_other_charge',
        ),
    ]
