# Generated by Django 3.2.9 on 2021-12-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0020_rename_purchase_order_other_charges_purchaseorder_purchase_order_other_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_order_order_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_order_other_charge',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
