# Generated by Django 3.2.9 on 2021-12-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInformation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='customer_last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer_login_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='national_id',
            new_name='customer_national_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_no',
            new_name='customer_phone_no',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='address',
            new_name='farmer_address',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='email',
            new_name='farmer_email',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='first_name',
            new_name='farmer_first_name',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='last_name',
            new_name='farmer_last_name',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='user',
            new_name='farmer_login_id',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='national_id',
            new_name='farmer_national_id',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='phone_no',
            new_name='farmer_phone_no',
        ),
    ]
