# Generated by Django 3.2.9 on 2021-12-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211218_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='order_delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='vendor_id',
            new_name='order_farmer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='order_login_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='reference_no',
            new_name='order_reference_no',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='order_id',
            new_name='order_item_order_id',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='product_id',
            new_name='order_item_product_id',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='quantity',
            new_name='order_item_quantity',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='total_cost',
            new_name='order_item_total_cost',
        ),
        migrations.RenameField(
            model_name='order_other_charge',
            old_name='charges_id',
            new_name='order_other_charge_charges_id',
        ),
        migrations.RenameField(
            model_name='order_other_charge',
            old_name='order_id',
            new_name='order_other_charge_order_id',
        ),
        migrations.RenameField(
            model_name='order_other_charge',
            old_name='total_price',
            new_name='order_other_charge_total_price',
        ),
        migrations.RenameField(
            model_name='othercharge',
            old_name='desc',
            new_name='other_charge_desc',
        ),
        migrations.RenameField(
            model_name='othercharge',
            old_name='name',
            new_name='other_charge_name',
        ),
        migrations.RenameField(
            model_name='othercharge',
            old_name='rate',
            new_name='other_charge_rate',
        ),
    ]
