# Generated by Django 3.2.9 on 2021-12-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211220_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_login_id',
            new_name='order_customer_login_id',
        ),
    ]
