# Generated by Django 3.2.9 on 2021-12-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_order_login_id_order_order_customer_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_farmer_id',
            new_name='order_customer_id',
        ),
    ]
