# Generated by Django 3.2.9 on 2021-12-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=' M-pesa Transaction code'),
        ),
    ]
