# Generated by Django 3.2.9 on 2021-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('M-pesa', 'M-pesa'), ('Cash', 'Cash')], max_length=10, verbose_name='Payment Mode'),
        ),
    ]
