# Generated by Django 3.2.9 on 2021-12-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_Order_id',
            field=models.CharField(max_length=10),
        ),
    ]
