# Generated by Django 3.2.9 on 2021-12-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_purchaseorder_purchase_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('M-pesa', 'M-pesa'), ('Cash', 'Cash')], max_length=10, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_order_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_Order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
