# Generated by Django 3.2.9 on 2021-12-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInformation', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='UserInformation.farmer'),
            preserve_default=False,
        ),
    ]
