# Generated by Django 3.2.9 on 2021-12-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211220_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_farmer_id',
            new_name='product_farmer_login_id',
        ),
    ]
